steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/learn-ci-cd/test-ci-cd:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/learn-ci-cd/test-ci-cd:$SHORT_SHA']
 
